//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_STT_RECPT_VOCHR_DEBIT
    {
        public double NetBalance { get; set; }
        public string Declaration { get; set; }
        public double TheDate { get; set; }
        public string RecordType { get; set; }
        public string RecordTypeArb { get; set; }
        public string RecordTypeEng { get; set; }
        public int ReceiptVoucherID { get; set; }
        public double DiscountAccountID { get; set; }
        public double DATECREATED { get; set; }
        public double DebitAccountID { get; set; }
        public string OppsiteAccountName { get; set; }
        public int BranchID { get; set; }
    }
}
