//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_CostCentersDetails
    {
        public int ID { get; set; }
        public int CostCenterID { get; set; }
        public int BranchID { get; set; }
        public int SubCostCenterID { get; set; }
        public string ArbCostCenterBranchName { get; set; }
        public string EngCostCenterBranchName { get; set; }

    }
}
