//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_CheckReceiptVoucherEng_Find
    {
        public int BranchID { get; set; }
        public int Check_ID { get; set; }
        public string Check_Date { get; set; }
        public Nullable<double> Account_ID { get; set; }
        public string Account_Name { get; set; }
        public Nullable<int> Cost_Center_ID { get; set; }
        public string Cost_Center_Name { get; set; }
        public string Receipt_Name { get; set; }
    }
}
