//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_DailyBoxArb_Find
    {
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> رقـم_الـيـومـيـة { get; set; }
        public Nullable<int> الـتـاريـخ { get; set; }
        public double رقم_الحسـاب { get; set; }
        public string اسم_الحسـاب { get; set; }
        public int رقم_م_تكلفة { get; set; }
        public string اسم_م_تكلفة { get; set; }
    }
}
