//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_SpendVoucherMaster
    {

        public int SpendVoucherID { get; set; }
        public int BranchID { get; set; }
        public int FacilityID { get; set; }
        public string SpendVoucherDate { get; set; }
        public string Notes { get; set; }
        public double CreditAccountID { get; set; }
        public double VatAccountID { get; set; }


        public double CreditGoldAccountID { get; set; }

        public double CreditAmount { get; set; }
        public double TotalGold { get; set; }
        public double VatAmountTotal { get; set; }

        public int CurencyID { get; set; }

        public string CurrencyName { get; set; }
        public decimal CurrencyPrice { get; set; }
        public decimal CurrencyEquivalent { get; set; }
        public double DiscountAccountID { get; set; }
       


        public double DiscountAmount { get; set; }
        public int InvoiceID { get; set; }
        public int DocumentID { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
        public int CostCenterID { get; set; }
        public int Posted { get; set; }
        public byte[] SpendImage { get; set; }
        public double RegistrationNo { get; set; }
        public string OperationTypeName { get; set; }
        public int DelegateID { get; set; }
        public double AmountForGold { get; set; }
        public double AmountForDiamond { get; set; }
        public double PaidOjore { get; set; }
        public double PaidDiamond { get; set; }
        public double PaidGold { get; set; }
         
            public Nullable<int> CurrencyID { get; set; }
        public List<Acc_SpendVoucherDetails> SpendVoucherDetails { get; set; }

    }
}
