//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_VariousVoucherDetails
    {
        public int ID { get; set; }
        public int VoucherID { get; set; }
        public int BranchID { get; set; }
        public double Debit { get; set; }
        public double Credit { get; set; }
        public double AccountID { get; set; }
        public string ArbAccountName { get; set; }
        public string EngAccountName { get; set; }
        public string Declaration { get; set; }
        public int CostCenterID { get; set; }
        public double AccountAssest { get; set; }
        public int FacilityID { get; set; }

        public int CurrencyID { get; set; }
        public string CurrencyName { get; set; }
        public double CurrencyPrice { get; set; }
        public double CurrencyEquivalent { get; set; }
        public Acc_VariousVoucherMaster VariousVoucherMaster { get; set; }




    }

 public partial class Acc_VariousVoucherMachinDetails
    {
        public int ID { get; set; }
        public int VoucherID { get; set; }
        public int BranchID { get; set; }
        public double Debit { get; set; }
        public double Credit { get; set; }

        
        public double AccountID { get; set; }
        public string ArbAccountName { get; set; }
        public string EngAccountName { get; set; }
        public string Declaration { get; set; }
        public int CostCenterID { get; set; }
        public double AccountAssest { get; set; }
        public int FacilityID { get; set; }
        public int FinalType { get; set; }
         public double DebitMatirial {get;set;}
         public double CreditMatirial{get;set;}
         public double DebitGold { get; set; }
         public double CreditGold { get; set; }
         public double DebitDiamond { get; set; }
         public double CreditDiamond { get; set; }
         public int CurrencyID{get;set;}
         public double CurrencyPrice{get;set;}
         public double CurrencyEquivalent { get; set; }
        public Acc_VariousVoucherMachinMaster VariousVoucherMaster { get; set; }




    }


}
