//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_DefaultAccountsTreeTemplate
    {
        public double AccountID { get; set; }
        public string ArbName { get; set; }
        public string EngName { get; set; }
        public double ParentAccountID { get; set; }
        public int AccountLevel { get; set; }
        public int AccountTypeID { get; set; }
    }
}
