//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_RestrictionTrancAction
    {
        public Nullable<double> THEDATE { get; set; }
        public Nullable<int> BRANCHID { get; set; }
        public Nullable<double> AccountID { get; set; }
        public string OPPSITEACCOUNTNAME { get; set; }
        public Nullable<double> DATECREATED { get; set; }
        public string RECORDTYPE { get; set; }
        public string RECORDTYPEARB { get; set; }
        public string RECORDTYPEENG { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public string DECLARATION { get; set; }
        public Nullable<double> CREDIT { get; set; }
        public Nullable<double> DEBIT { get; set; }
    }
}
