//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_STT_SALE_INV_RET_DEBIT
    {
        public Nullable<double> TOTALBALANCE { get; set; }
        public Nullable<double> TOTALDISCOUNT { get; set; }
        public Nullable<double> AdditionalValue { get; set; }
        public string DECLARATION { get; set; }
        public double THEDATE { get; set; }
        public double RegDate { get; set; }
        public string RECORDTYPE { get; set; }
        public string RecordTypeArb { get; set; }
        public string RecordTypeEng { get; set; }
        public int InvoiceID { get; set; }
        public double DEBITACCOUNT { get; set; }
        public double CREDITACCOUNT { get; set; }
        public Nullable<double> AdditionalAccount { get; set; }
        public string OPPSITEACCOUNTNAME { get; set; }
        public int BRANCHID { get; set; }
    }
}
