//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_DailyBoxEng_Find
    {
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> Daily_ID { get; set; }
        public Nullable<int> Date { get; set; }
        public double Account_ID { get; set; }
        public string Account_Name { get; set; }
        public int Cost_Center_ID { get; set; }
        public string Cost_Center_Name { get; set; }
    }
}
