//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_DeclaringIncomeAccountsTamplate
    {
        public double AccountID { get; set; }
        public string DeclareAccountName { get; set; }
        public string AccountArbName { get; set; }
        public string AccountEngName { get; set; }
    }
}
