//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_CheckSpendVoucherDetails
    {
        public int ID { get; set; }
        public int CheckSpendVoucherID { get; set; }
        public int BranchID { get; set; }
        public double AccountID { get; set; }
        public string AccountName { get; set; } 
        public double DebitAmount { get; set; } 
        public string Declaration { get; set; }
        public string ReceiptName { get; set; }
        public int CostCenterID { get; set; }
        public int FacilityID { get; set; }
        public Acc_CheckSpendVoucherMaster CheckSpendVoucherMaster { get; set; }


    }
}
