//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    public partial class Acc_CheckReceiptVoucherMaster
    {
        public int CheckReceiptVoucherID { get; set; }
        public int BranchID { get; set; }
        public string CheckReceiptVoucherDate { get; set; }
        public string Notes { get; set; }
        public double DebitAccountID { get; set; }
        public double DebitAmount { get; set; }
        public double DiscountAccountID { get; set; }
        public double DiscountAmount { get; set; }
        public int InvoiceID { get; set; }
        public int DocumentID { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
        public int DelegateID { get; set; }
        public byte[] SpendImage { get; set; }
        public double RegistrationNo { get; set; }
       
        public int CurrencyID { get; set; }
        public string CurrencyName { get; set; }
        public decimal CurrencyPrice { get; set; }
        public decimal CurrencyEquivalent { get; set; }
        public string HijriDate { get; set; }
        public string GreDate { get; set; }
        public string BeneficiaryName { get; set; }
        public string WroteInCity { get; set; }
        public int BankID { get; set; }
        public int FacilityID { get; set; }
        public string OperationTypeName { get; set; }
        public List<Acc_CheckReceiptVoucherDetails> CheckReceiptVoucherDetails { get; set; }
         
    }
}
