//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsDaily
    {
        public double ACC_CODE { get; set; }
        public string Acc_name { get; set; }
        public int THLEVEL { get; set; }
        public double debt { get; set; }
        public double credit { get; set; }
        public int posted { get; set; }
        public int BranchNum { get; set; }
        public double RegistrationDate { get; set; }
        public int TransYear { get; set; }
        public int MounthNum { get; set; }
        public double TRANNO { get; set; }
        public double RegistrationNo { get; set; }
        public int Cancel { get; set; }
    }
}
