//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arc_ArchiveForm
    {
        public int ID { get; set; }
        public int BranchID { get; set; }
        public string DocNo { get; set; }
        public int Important { get; set; }
        public double DocDate { get; set; }
        public int DocType { get; set; }
        public int PreparedBy { get; set; }
        public string Subject { get; set; }
        public string Notes { get; set; }
        public string AttachmentInfo { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
    }
}
