//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ast_AssetsDeclaration
    {
        public double AssetGroupID { get; set; }
        public double AssetAccountID { get; set; }
        public int BranchID { get; set; }
        public string ArbName { get; set; }
        public string EngName { get; set; }
        public double AssetPurchaseValue { get; set; }
        public double DepreciationStartDate { get; set; }
        public int AnnualDepreciationRate { get; set; }
        public string AssetDecription { get; set; }
        public string SupplierInvoiceID { get; set; }
        public string AssetSerialNumber { get; set; }
        public string SupplierName { get; set; }
        public string SupplyInfo { get; set; }
        public string AssetStatus { get; set; }
        public int DepreciationType { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
        public double CreditAccount { get; set; }
        public double DepreciationAccount { get; set; }
        public double ExpenceAccount { get; set; }
        public int CostCenterID { get; set; }
    }
}
