//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinic_InsuranceCard
    {
        public double ID { get; set; }
        public string CardIDNo { get; set; }
        public double PateintID { get; set; }
        public double CompanyID { get; set; }
        public double EnduranceRatio { get; set; }
        public string NetWorkName { get; set; }
        public double Limit { get; set; }
        public string CompanyName { get; set; }
        public double UpTo { get; set; }
        public string PolicyNo { get; set; }
        public double ExpireDate { get; set; }
        public int IssuseNo { get; set; }
        public int Cancel { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditDate { get; set; }
        public double EditTime { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
    }
}
