//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicPatientDaignose
    {
        public double Sn { get; set; }
        public double PatientCaseID { get; set; }
        public int BranchID { get; set; }
        public double VisitID { get; set; }
        public double ICD10ID { get; set; }
        public string Notes { get; set; }
    }
}
