//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinic_Answer
    {
        public double PatientID { get; set; }
        public int QuestionID { get; set; }
        public int Done { get; set; }
        public string Notes { get; set; }
        public int BranchID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<double> RegDate { get; set; }
        public Nullable<double> RegTime { get; set; }
        public Nullable<int> EditUserID { get; set; }
        public Nullable<double> EditDate { get; set; }
        public Nullable<double> EditTime { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public Nullable<int> Cancel { get; set; }
    }
}
