//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLINIC_PatientFile
    {
        public double PateintID { get; set; }
        public int BranchID { get; set; }
        public string ArbName { get; set; }
        public string EngName { get; set; }
        public string NoID { get; set; }
        public int Sex { get; set; }
        public int MaritalStatus { get; set; }
        public double BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public int Nationality { get; set; }
        public int Religions { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string EmreginsTel { get; set; }
        public string Notes { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditDate { get; set; }
        public double EditTime { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
        public byte[] PatientImage { get; set; }
        public double Acc_Code { get; set; }
    }
}
