//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicMedicalList
    {
        public int ID { get; set; }
        public string ArbName { get; set; }
        public string EngName { get; set; }
        public string UseWay { get; set; }
        public string PharmaceuticalForm { get; set; }
        public string Size { get; set; }
        public string PackageType { get; set; }
        public int Cancel { get; set; }
    }
}
