//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColorsSettings
    {
        public string StyleManager { get; set; }
        public string FormBackColorRed { get; set; }
        public string FormBackColorGreen { get; set; }
        public string FormBackColorBlue { get; set; }
        public string WafeTopTextBoxForeColor { get; set; }
        public string WafeTopTextBoxBackColor { get; set; }
        public string ButtonForeColor { get; set; }
        public string ButtonBackColor { get; set; }
        public string WafeTextBoxImportantFieldForeColor { get; set; }
        public string WafeTextBoxImportantFieldBackColor { get; set; }
        public string BorderedLabelForeColor { get; set; }
        public string BorderedLabelBackColor { get; set; }
        public string NormalLabelForeColor { get; set; }
        public string NormalLabelBackColor { get; set; }
        public string GridBackgroundColor { get; set; }
        public string GridCellBackColor { get; set; }
        public string GridCellForeColor { get; set; }
        public string GridCellLockedForeColor { get; set; }
        public string GridCellLockedBackColor { get; set; }
        public string GridHeaderForeColor { get; set; }
        public string GridHeaderBackColor { get; set; }
        public string TabBackColor { get; set; }
        public string TreeViewForeColor { get; set; }
        public string TreeViewBackColor { get; set; }
    }
}
