//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyHeader
    {
        public int BranchID { get; set; }
        public byte[] pic { get; set; }
        public string imageHref { get; set; }
        public string CompanyArbName { get; set; }
        public string CompanyEngName { get; set; }
        public string ActivityArbName { get; set; }
        public string ActivityEngName { get; set; }
        public string ArbAddress { get; set; }
        public string EngAddress { get; set; }
        public string ArbTel { get; set; }
        public string EngTel { get; set; }
        public string ArbFax { get; set; }
        public string EngFax { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
        public int FacilityID { get; set; }
        public int ID { get; set; }
        public string footer { get; set; }

    }
}
