//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailedDailyTransactionArb
    {
        public string RecordType { get; set; }
        public int ID { get; set; }
        public double TheDate { get; set; }
        public double TheTime { get; set; }
        public int MethodeID { get; set; }
        public string MethodeName { get; set; }
        public string Declaration { get; set; }
        public string UserName { get; set; }
        public string AccountName { get; set; }
        public string OppsiteAccountName { get; set; }
        public int BranchID { get; set; }
    }
}
