//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dress_InvoiceMaster
    {
        public double InvoiceID { get; set; }
        public double Manual { get; set; }
        public int TypesClothingID { get; set; }
        public int ModelID { get; set; }
        public int DressMakerID { get; set; }
        public string SpecificationsPockets { get; set; }
        public string TypeDressMaker { get; set; }
        public string Notes { get; set; }
        public int Cancel { get; set; }
        public byte[] ModelImage { get; set; }
        public int BranchNum { get; set; }
        public Nullable<double> HijriDeliveryDate { get; set; }
        public Nullable<double> Cashe { get; set; }
        public Nullable<double> DeliveryDate { get; set; }
        public Nullable<double> Datehijritransdate { get; set; }
        public Nullable<double> transdate { get; set; }
        public Nullable<double> CustomerID { get; set; }
        public Nullable<double> Remaining { get; set; }
        public Nullable<double> Receve { get; set; }
        public string Desc1 { get; set; }
        public string Desc2 { get; set; }
        public string Desc3 { get; set; }
        public string Desc4 { get; set; }
        public string Desc5 { get; set; }
        public string Desc6 { get; set; }
        public string Desc7 { get; set; }
        public string Desc8 { get; set; }
        public string Desc9 { get; set; }
        public string Desc10 { get; set; }
        public string Release { get; set; }
        public Nullable<int> DressInvoiceID { get; set; }
        public Nullable<int> OutOnBondsID { get; set; }
    }
}
