//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dress_FormsGroups
    {
        public int FormsGroupID { get; set; }
        public double DressMakerGroupID { get; set; }
        public byte[] FormsGroupImage { get; set; }
        public string ArbName { get; set; }
        public string EngName { get; set; }
        public int Cancel { get; set; }
        public int BranchID { get; set; }
    }
}
