//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralSettings
    {
        public int UsingExpiryDate { get; set; }
        public double AllowedPercentDiscount { get; set; }
        public int ItemProfit { get; set; }
        public string CalcStockBy { get; set; }
        public int MaxBarcodeDigits { get; set; }
        public string WayOfOutItems { get; set; }
        public int AutoCalcFixAssetsDepreciation { get; set; }
        public int UsingItemsSerials { get; set; }
        public string BackupPath { get; set; }
        public int DepreciationType { get; set; }
        public int BranchID { get; set; }
        public int FacilityID { get; set; }
        public int PriceDigits { get; set; }
        public int QtyDigits { get; set; }
        public int ItemDigits { get; set; }
        public int ItemPriceDigits { get; set; }
        public int InventoryType { get; set; }
        public int CostCalculationType { get; set; }

    }
}
