//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotels_OccupancyTable
    {
        public int ID { get; set; }
        public int BranchID { get; set; }
        public int TotalRooms { get; set; }
        public int VacantRooms { get; set; }
        public int OccupeidRooms { get; set; }
        public int ReservedRooms { get; set; }
        public int O_O_Rooms { get; set; }
        public double TheDate { get; set; }
    }
}
