//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EmployeeFile
    {
        public long EmployeeID { get; set; }
        public Nullable<double> ParentAccountID { get; set; }
        public int FacilityID { get; set; }
        public int BranchID { get; set; }
        public string ArbName { get; set; }
        public string EngName { get; set; }
        public int FootprintEmpID { get; set; }
        public int Sex { get; set; }
        public int MaritalStatus { get; set; }
        public double BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public int Nationality { get; set; }
        public int Religions { get; set; }
        public int WorkType { get; set; }
        public int Occupation { get; set; }
        public int IqamaOccupation { get; set; }
        public string CurrentSponsor { get; set; }
        public int ContractType { get; set; }
        public double BeginningDate { get; set; }
        public double ContractEnd { get; set; }
         
        public double DateStartWork { get; set; }

        public double DateIssuanceID { get; set; }

        public int Administration { get; set; }
        public int Department { get; set; }
        public string BankAccountID { get; set; }
        public int PaymentMethod { get; set; }
        public string EmpNotes { get; set; }

        public string CurrentSponsorMobile { get; set; }
        public int TerminationReason { get; set; }
        public double ReportingDate { get; set; }
        public double ValidFromDate { get; set; }
        public string LeaveNotes { get; set; }
        public string WorkAddress { get; set; }
        public string WorkTel { get; set; }
        public string WorkMobile { get; set; }

        public string CardID { get; set; }
        public string WorkEmail { get; set; }
        public string CompanyVehicle { get; set; }
        public string HomeWorkDistance { get; set; }
        public string AddressNotes { get; set; }
        public double WorkingHours { get; set; }
        public string HomeAddress { get; set; }
        public string HomeTel { get; set; }
        public string HomeMobil { get; set; }
        public byte[] EmpImage { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
        public int Termination { get; set; }
        public int StopSalary { get; set; }
        public int ClinicID { get; set; }
        public int Emptype { get; set; }
        public double CheckSpendDate { get; set; }
        public double AccountMeter { get; set; }
        public int CostCenterID { get; set; }
        public double? OnAccountID { get; set; }
        public int StopAccount { get; set; }
        public int ScientificDisciplines { get; set; }
        public decimal AllowQTYPer { get; set; }
    }
}
