//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EmployeeIDsImages
    {
        public int SN { get; set; }
        public int BranchID { get; set; }
        public double EmployeeID { get; set; }
        public string IDNo { get; set; }
        public int ImageID { get; set; }
        public byte[] TheImage { get; set; }
    }
}
