//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_RecordAbsent
    {
        public int ID { get; set; }
        public double EmployeeID { get; set; }
        public double TheDate { get; set; }
        public string OnAccountNotes { get; set; }
        public int Cancel { get; set; }
        public int Mounth { get; set; }
        public int Year { get; set; }
    }
}
