//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_SalariesHistory
    {
        public double EmployeeID { get; set; }
        public int BranchID { get; set; }
        public int Month { get; set; }
        public int AbsencesAccordingTo { get; set; }
        public double TheDate { get; set; }
        public string EmployeeName { get; set; }
        public string Department { get; set; }
        public int Days { get; set; }
        public Nullable<int> OfferTimeHours { get; set; }
        public string OfferTime { get; set; }
        public string Allowance0 { get; set; }
        public string Allowance1 { get; set; }
        public string Allowance2 { get; set; }
        public string Allowance3 { get; set; }
        public string Allowance4 { get; set; }
        public string Allowance5 { get; set; }
        public string Allowance6 { get; set; }
        public string Allowance7 { get; set; }
        public string Allowance8 { get; set; }
        public string Allowance9 { get; set; }
        public string Allowance10 { get; set; }
        public string Allowance11 { get; set; }
        public string Allowance12 { get; set; }
        public string Allowance13 { get; set; }
        public string Allowance14 { get; set; }
        public string Allowance15 { get; set; }
        public string Allowance16 { get; set; }
        public string Allowance17 { get; set; }
        public string Allowance18 { get; set; }
        public string Allowance19 { get; set; }
        public string Allowance20 { get; set; }
        public double TotalAllowance { get; set; }
        public int AbsenceDays { get; set; }
        public string Absence { get; set; }
        public string Deduction0 { get; set; }
        public string Deduction1 { get; set; }
        public string Deduction2 { get; set; }
        public string Deduction3 { get; set; }
        public string Deduction4 { get; set; }
        public string Deduction5 { get; set; }
        public string Deduction6 { get; set; }
        public string Deduction7 { get; set; }
        public string Deduction8 { get; set; }
        public string Deduction9 { get; set; }
        public string Deduction10 { get; set; }
        public string Deduction11 { get; set; }
        public string Deduction12 { get; set; }
        public string Deduction13 { get; set; }
        public string Deduction14 { get; set; }
        public string Deduction15 { get; set; }
        public string Deduction16 { get; set; }
        public string Deduction17 { get; set; }
        public string Deduction18 { get; set; }
        public string Deduction19 { get; set; }
        public string Deduction20 { get; set; }
        public double TotalDeductions { get; set; }
        public double SalariesNet { get; set; }
        public string PaymentMethode { get; set; }
        public string ChequeNo { get; set; }
        public double ChequeDate { get; set; }
        public string BankAccountNo { get; set; }
        public int Year { get; set; }
        public int EntitlementVoucherID { get; set; }
        public int ReceiptVoucherID { get; set; }
        public int SalarySpendVoucherID { get; set; }
        public double OnAccount { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
    }
}
