//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public int ID { get; set; }
        public string DBName { get; set; }
        public int BranchID { get; set; }
        public int UserID { get; set; }
        public string Password { get; set; }
        public int Status { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public string ComputerInfo { get; set; }
    }
}
