

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;

    public class Manu_CloseOrdersMaster
    {
        public int CommandID { get; set; }
        public int CommandStageID { get; set; }
        public string OrderID { get; set; }
        public int BranchID { get; set; }
        public int FacilityID { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
        public double CommandDate { get; set; } 
        public double BeforeStoreID { get; set; }
        public double AfterStoreID { get; set; }    
        public string Notes { get; set; }  
        public List<Manu_CloseOrdersDetails> Manu_Detils { get; set; }

        public int TypeStageID { get; set; }

        public decimal TotalOrderQTY { get; set; }

        public int CurrencyID { get; set; }

        public int RepetID { get; set; }

        public int Posted { get; set; }
    }
}
