//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    public partial class Manu_OrderRestriction
    {
        public string OrderID { get; set; }
        public string OrderDate { get; set; }
        public double CustomerID { get; set; }
        public string CustomerName { get; set; }
        public double GuidanceID { get; set; }
        public float DelegateID { get; set; }
        public int TypeOrdersID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public Nullable<double> RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int TypeAuxiliaryMatirialID { get; set; }
        public int TypeID { get; set; }
        public int Cancel { get; set; }
        public int UserID { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal >GoldQTYCloves { get; set; }
        public Nullable< decimal> BonesPriceOrder { get; set; }

        public string ImageCode { get; set; }
    }
}
