
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Manu_ManufacturingTheFactoryDetails
    {
        public int ID { get; set; }
        public Nullable<int> ManufacturingCastingID { get; set; }
        public Nullable<double> Givinghim { get; set; }
        public Nullable<double> Recivefromhisjob { get; set; }
        public Nullable<double> RecivefromReturn { get; set; }
        public Nullable<double> TheLost { get; set; }
        public Nullable<double> Allowed { get; set; }
        public Nullable<double> TheDifference { get; set; }
        public Nullable<double> TheTree { get; set; }
        public Nullable<double> PriceTheGram { get; set; }
        public Nullable<double> TheAmount { get; set; }
        public string TheDescription { get; set; }
        public Nullable<double> LostFlage { get; set; }
        public Nullable<double> DateWork { get; set; }
    }
}

