//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;

   public class Manu_AuxiliaryMaterialsMaster
    {
        public int CommandID { get; set; }
        public int BranchID { get; set; }
        public int FacilityID { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
        public int ReferanceID { get; set; }
        public double CommandDate { get; set; }    
        public double CustomerID { get; set; }
        public double EmployeeStokID { get; set; }
        public double StoreID { get; set; }

        public double AccountID { get; set; }
        public int CostCenterID { get; set; }
        public double FactorID { get; set; }
        public int DelegetID { get; set; }
        public int CurrencyID { get; set; }
        public string Notes { get; set; }
        public int TypeCommand { get; set; }

       public List<Manu_AuxiliaryMaterialsDetails> Menu_F_AuxiliaryMaterials { get; set; }



    }
}
