//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manu_ItemManufacturing_Details
    {
        public int ID { get; set; }
        public int ManufacturingID { get; set; }
        public string BarCode { get; set; }
        public double QTY { get; set; }
        public double WasteQTY { get; set; }
    }
}
