
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;

    public class Manu_AfforestationFactoryMaster
    {
        public int  CommandID { get; set; }
        public string OrderID { get; set; }
        public int BranchID { get; set; }
        public int FacilityID { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }

        public double DateBefore { get; set; }
        public double DateAfter { get; set; }
        public double StoreIDBefore { get; set; }
        public double AfterAccountID { get; set; }
        public int CostCenterID { get; set; }
        public double FactorID { get; set; }
        public int CurrencyID { get; set; }
        public string Notes { get; set; }
        public int Posted { get; set; }
        public int PeriodDay { get; set; }
        public string StoreMangerBefore { get; set; }
        public double AfterFactorID { get; set; }
        public decimal EquQty { get; set; }
        public decimal TotalQTY { get; set; }
        public decimal GoldQTYCloves { get; set; }

        public List<Manu_AfforestationFactoryDetails> Manu_CadWaxFactorys { get; set; }

        public Nullable<int>  TypeStageID { get; set; }

        public List<Manu_AllOrdersDetails> Manu_OrderDetils { get; set; }
    }
}
