
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Manu_TheFactoryManufacturing_Master
    {
        public int ManufacturingCastingID { get; set; }
        public double EmployeeID { get; set; }
        public Nullable<double> Occupation { get; set; }
        public Nullable<double> ToDate { get; set; }
        public double ManufacturingCastingDate { get; set; }
        public string Notes { get; set; }
        public Nullable<double> UserID { get; set; }
        public Nullable<double> RegDate { get; set; }
        public Nullable<double> RegTime { get; set; }
        public Nullable<int> EditUserID { get; set; }
        public Nullable<double> EditDate { get; set; }
        public Nullable<double> EditTime { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public Nullable<int> Cancel { get; set; }
        public Nullable<double> TotalDebit { get; set; }
        public Nullable<double> TotalCredit { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> LostQty { get; set; }
        public Nullable<double> AllowQty { get; set; }
        public Nullable<double> TotalDebitDaimond { get; set; }
        public Nullable<double> CreditDaimond { get; set; }
        public Nullable<double> RecivefromReturn { get; set; }
        public Nullable<double> PercentAllow { get; set; }
    }
}
