
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    public partial class Manu_CloseOrdersDetails
    {
        public int CommandID { get; set; }
        public int BranchID { get; set; }
        public int FacilityID { get; set; }
        public string BarCode { get; set; }
        public int ItemID { get; set; }
        public string ArbItemName { get; set; }
        public string EngItemName { get; set; }
        public int SizeID { get; set; }
        public string ArbSizeName { get; set; }
        public string EngSizeName { get; set; }
        public decimal QTY { get; set; }
        public double CostPrice { get; set; }
        public double TotalCost { get; set; }
        public int TypeOprationID { get; set; }

    }
}
