
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    public partial class Menu_FactoryRunCommandMaster
    {
        public string Barcode { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> ComandID { get; set; }
        public int CostCenterID { get; set; }
        public Nullable<double> ComandDate { get; set; }
        public Nullable<double> BranchID { get; set; }
        public Nullable<double> EmployeeID { get; set; }
        public Nullable<double> CustomerID { get; set; }
        public Nullable<double> piece { get; set; }
        public Nullable<double> EmpFactorID { get; set; }
        public Nullable<double>  DelegateID { get; set; }
        public Nullable<double> Goldweight1 { get; set; }
        public Nullable<double> GivenDate { get; set; }
        public Nullable<double> ReciveDate { get; set; }
        public Nullable<double> GivenTime { get; set; }
        public Nullable<double> TimeRecive { get; set; }
        public Nullable<double> EmployeeStokID { get; set; }
        public Nullable<double> GoldWeight { get; set; }
        public Nullable<double> WeightDaimond { get; set; }
        public Nullable<double> WeightBaguettes { get; set; }
        public Nullable<double> StoneWeight { get; set; }
        public Nullable<double> netGoldWeight { get; set; }
        public Nullable<double> TotalLost { get; set; }
        public Nullable<double> TotalEquvelentGold { get; set; }
        public Nullable<double> TotalDaimondSecound { get; set; }
        public Nullable<double> SigntureDate { get; set; }
        public Nullable<double> SigntureTime { get; set; }
        public string Notes { get; set; }
        public Nullable<double> EmployeeIDCompuningID { get; set; }
        public Nullable<int> Cancel { get; set; }

        public Nullable<int> CurrencyID { get; set; }
         
        public string CurrencyName { get; set; }

        public byte[] InvoiceImage { get; set; }
        public Nullable<double> TheType { get; set; }
        public Nullable<int> ComandStatues { get; set; }
        public Nullable<double> DebditGoldAccountID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<double> fromAccountID { get; set; }
        public byte[] InvoiceImage2 { get; set; }
        public Nullable<double> SpendAmount { get; set; }
        public Nullable<double> EmpPrentagID { get; set; }
        public Nullable<double> EmpPolishnID { get; set; }
        public Nullable<double> GoldDebit { get; set; }
        public Nullable<double> GoldCredit { get; set; }
        public Nullable<double> GoldCompundNet { get; set; }
        public Nullable<int> ThefactoriID { get; set; }
        public Nullable<int> OpretionID { get; set; }
        public Nullable<int> TypeStageID { get; set; }
        public string PeiceName { get; set; }
        public int FacilityID { get; set; }

        //الحسابات للتابات
        public Nullable<double> AccountIDFactory { get; set; }
        public Nullable<double> StoreIDFactory { get; set; }
        public Nullable<double> EmployeeStokIDFactory { get; set; }
        public Nullable<double> EmpIDFactor { get; set; }

        public Nullable<double> AccountIDPrentage { get; set; }
        public Nullable<double> StoreIDPrentage { get; set; }
        public Nullable<double> EmployeeStokIDPrentage { get; set; }
        public Nullable<double> EmpIDPrentage { get; set; }


        public Nullable<double> AccountIDBeforCompond { get; set; }
        public Nullable<double> StoreIDBeforComond { get; set; }
        public Nullable<double> EmployeeStokIDBeforCompond { get; set; }
        public Nullable<double> EmpIDBeforCompond { get; set; }

        public Nullable<double> AccountIDAfterCompond { get; set; }
        public Nullable<double> EmployeeStokIDAfterCompond { get; set; }
        public Nullable<double> StoreIDAfterComond { get; set; }
        public Nullable<double> EmpIDAfterCompond { get; set; }

        public Nullable<double> AccountIDAdditions { get; set; }
        public Nullable<double> StoreIDAdditions { get; set; }
        public Nullable<double> EmployeeStokIDAdditions { get; set; }
        public Nullable<double> EmpIDAdditions { get; set; }

        public Nullable<double> AccountIDPolishing { get; set; }
        public Nullable<double> StoreIDPolishing { get; set; }
        public Nullable<double> EmployeeStokIDPolishing { get; set; }
        public Nullable<double> EmplooyIDPolishing { get; set; }

        public Nullable<double> AccountIDBarcodeItem { get; set; }
        public Nullable<double> StoreIDBarcod { get; set; }
        public Nullable<double> EmployeeStokIDBarcode { get; set; }
        public Nullable<int> PollutionTypeID { get; set; }

        public List<Menu_FactoryRunCommandPrentagAndPulishn> Menu_F_Prentag { get; set; }
        public List<Menu_FactoryRunCommandTalmee> Menu_F_Talmee { get; set; } 
        public List<Menu_FactoryRunCommandCompund> Menu_F_Compund { get;set;}
        public List<Menu_FactoryRunCommandSelver> Menu_F_Selver { get; set; }
        public List<Menu_FactoryRunCommandfactory> Menu_F_Factory { get; set; }
        public List<Manu_ProductionExpensesDetails> Menu_F_ProductionExpenses { get; set; }

        public List<Menu_FactoryRunCommandDismant> Menu_F_Dismant { get; set; }

        public int PrntageTypeID { get; set; }
        public int Posted { get; set; }
        public int TypeStageBeforeID { get; set; }

        public List<Manu_AllOrdersDetails> Manu_OrderDetils { get; set; }
    }
}
