
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    public partial class Menu_FactoryRunCommandCompund
    {
        public int ID { get; set; }
        public Nullable<double> ComandID { get; set; }
        public string BarcodCompond { get; set; }
        public int ItemID { get; set; }

        public string TypeSton { get;set;}
        public string ArbItemName { get; set; }
        public string EngItemName { get; set; }
        public int SizeID { get; set; }
        public string ArbSizeName { get; set; }
        public string EngSizeName { get; set; }
        public decimal CostPrice { get; set; }

        public float GoldDebit { get; set; }
        public float GoldCredit { get; set; }

        public float ComStoneCom { get; set; }
        public decimal ComWeightSton { get; set; }

        public double ComStoneNumin { get; set; }
        public double ComWeightStonin { get; set; }
        public double ComStoneNumout { get; set; }
        public double ComWeightStonOUt { get; set; }
        public double ComStoneNumlas { get; set; }
        public Nullable<int> Cancel { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public double ComWeightStonLas { get; set; }
        
        public decimal ComWeightStonAfter { get; set; }
        public float SalePrice { get; set; }
        public Nullable<float> InvoiceImage { get; set; }
        public Nullable<double> FromAccountID { get; set; }
        public string FromAccountName { get; set; }     
        public Nullable<double> EmpCompondID { get; set; }
        public string EmpCompundName { get; set; }
        public string ComSignature { get; set; }
   
        public Nullable<float> GoldCompundNet { get; set; }

        public int RegDate { get; set; }
        public double RegTime { get; set; }
        public string ComputerInfo { get; set; }
        public List<Menu_FactoryRunCommandPrentagAndPulishn> Menu_F_PrentagAndPulishn { get; set; }

        public int EditUserID { get; set; }

        public double EditTime { get; set; }

        public int EditDate { get; set; }

        public string EditComputerInfo { get; set; }
        public int TypeOpration { get; set; }
        public int UserID { get; set; }
        public int TypeID { get; set; }

        public DateTime DebitDate { get; set; }

        public string DebitTime { get; set; }
        public bool ShownInNext { get; set; }
    }
}
