//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
  
       public partial class   Menu_ProductionExpensesAcconts
    {
        public int ComandID { get; set; }
        public double AccountID { get; set; }
        public string AccountName { get; set; }
        public int BranchID { get; set; }
        public int Cancel { get; set; }
        public Menu_ProductionExpensesAcconts Manu_Detils { get; set; }

    }
}
