//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    public class Manu_ProductionExpensesDetails
    {
        public Nullable<double> ComandID { get; set; }
        public double AccountID { get; set; }
        public string AccountName { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
        public decimal Evaluation { get; set; }
        public int TypeExpenssID { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Cancel { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public Nullable<int> EditUserID { get; set; }
        public Nullable<float> EditDate { get; set; }
        public Nullable<double> EditTime { get; set; }
        public Nullable<float> RegDate { get; set; }
        public Nullable<float> UserID { get; set; }
        public string EditComputerInfo { get; set; }
        public string ComputerInfo { get; set; }
        public Nullable<double> RegTime { get; set; } 
    }
}
