//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageTimerDetail
    {
        public int ID { get; set; }
        public int ReportID { get; set; }
        public int DayID { get; set; }
        public string SendingTime { get; set; }
        public Nullable<bool> Email { get; set; }
        public Nullable<bool> SMS { get; set; }
        public Nullable<int> BranchID { get; set; }
    }
}
