//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageTimerMaster
    {
        public int ReportID { get; set; }
        public string rptName { get; set; }
        public string ArbName { get; set; }
        public string EngName { get; set; }
        public Nullable<bool> IncludeHeader { get; set; }
        public string SubReportName { get; set; }
    }
}
