//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Others_RequestExchangeFor_Master
    {
        public int RequestID { get; set; }
        public int BranchID { get; set; }
        public Nullable<int> MethodID { get; set; }
        public double AccountID { get; set; }
        public double TheDate { get; set; }
        public double ExchangeDate { get; set; }
        public string PersonName { get; set; }
        public double RequestAmount { get; set; }
        public string ExchangeReason { get; set; }
        public Nullable<double> CheckDate { get; set; }
        public string CheckID { get; set; }
        public Nullable<int> BankID { get; set; }
        public string BankAccount { get; set; }
        public string BankTransferDate { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
    }
}
