//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Other_ProjectOutonBail
    {
        public int ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> SizeID { get; set; }
        public Nullable<double> QTY { get; set; }
        public Nullable<double> CostPrice { get; set; }
        public string BarCode { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
    }
}
