//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent_SalesInvoiceTranseMaster
    {
        public int InvoiceID { get; set; }
        public int BranchID { get; set; }
        public double InvoiceDate { get; set; }
        public int MethodeID { get; set; }
        public double CustomerID { get; set; }
        public int CostCenterID { get; set; }
        public int SellerID { get; set; }
        public int StoreID { get; set; }
        public double DelegateID { get; set; }
        public string Notes { get; set; }
        public double DiscountOnTotal { get; set; }
        public double DebitAccount { get; set; }
        public double CreditAccount { get; set; }
        public double DiscountDebitAccount { get; set; }
        public int FromCashierScreen { get; set; }
        public int CloseCashier { get; set; }
        public double CloseCashierDate { get; set; }
        public string NetProcessID { get; set; }
        public string CheckID { get; set; }
        public double CheckSpendDate { get; set; }
        public double WarningDate { get; set; }
        public int DailyID { get; set; }
        public string OrderType { get; set; }
        public int SectionID { get; set; }
        public int TableID { get; set; }
        public int NeedReview { get; set; }
        public string ReviewType { get; set; }
        public int IsSendReview { get; set; }
        public string WorkDetails { get; set; }
        public string Status { get; set; }
        public int DocumentID { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
        public double EmployeeID { get; set; }
        public double PateintID { get; set; }
        public double TempInvoiceID { get; set; }
        public double EnduranceRatio { get; set; }
    }
}
