//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent_SalesInvoiceReciveDetails
    {
        public int ID { get; set; }
        public int InvoiceID { get; set; }
        public string Send { get; set; }
        public string SendTo { get; set; }
        public string TypeSale { get; set; }
        public int Qty { get; set; }
        public string Mobile { get; set; }
        public double Price { get; set; }
        public string Notes { get; set; }
        public int BranchID { get; set; }
    }
}
