//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int ID { get; set; }
        public string ReportName { get; set; }
        public string ArbCaption { get; set; }
        public string EngCaption { get; set; }
        public string MenuName { get; set; }
        public int IsClientPurchaseIt { get; set; }
    }
}
