//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Res_Parties_Master
    {
        public int OrderID { get; set; }
        public int BranchID { get; set; }
        public double OrderDate { get; set; }
        public double DeliveryDate { get; set; }
        public double NotificationDate { get; set; }
        public string MealTime { get; set; }
        public string MealType { get; set; }
        public double CustomerID { get; set; }
        public double NetBalance { get; set; }
        public double DiscountValue { get; set; }
        public double PaidAmount { get; set; }
        public int VoucherID { get; set; }
        public string Notes { get; set; }
        public int Status { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
    }
}
