//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Res_ItemsInsurance_Details
    {
        public int ID { get; set; }
        public int InsuranceID { get; set; }
        public int BranchID { get; set; }
        public string BarCode { get; set; }
        public int ItemID { get; set; }
        public int SizeID { get; set; }
        public double QTY { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
        public int StoreID { get; set; }
        public int CostPrice { get; set; }
    }
}
