//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Suppliers
    {
        public int SupplierID { get; set; }
        public Nullable<double> AccountID { get; set; }
        public int StopAccount { get; set; }
        public string CommercialRegister { get; set; }
        public Nullable<double> ParentAccountID { get; set; }
        public int BranchID { get; set; }
        public int FacilityID { get; set; }
   public int NationalityID { get; set; }

        public string ArbName { get; set; }
        public string EngName { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Notes { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
        public string BankAccountNo { get; set; }
        public string BankName { get; set; }
        public string AuthorizedPerson { get; set; }
        public string VATID { get; set; }
    }
}
