//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_TotalPurchase
    {
        public int InvoiceID { get; set; }
        public double InvoiceDate { get; set; }
        public string BarCode { get; set; }
        public double QTY { get; set; }
        public double CostPrice { get; set; }
        public double TotalCost { get; set; }
        public double Discount { get; set; }
        public int BranchID { get; set; }
    }
}
