//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_BarCodeForPurchaseReturnEng_Find
    {
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> SupplierInvoiceID { get; set; }
        public int StoreID { get; set; }
        public int InvoiceID { get; set; }
        public string BarCode { get; set; }
        public int Item_ID { get; set; }
        public string Item_Name { get; set; }
        public int Unit_ID { get; set; }
        public string Unit_Name { get; set; }
        public string Expiry_Date { get; set; }
        public string Store_Name { get; set; }
    }
}
