//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_PriceOffersArb
    {
        public int BranchID { get; set; }
        public double رقم_العرض { get; set; }
        public string تاريخ_العرض { get; set; }
        public int فترة_العرض { get; set; }
        public string الحالة { get; set; }
        public string اسـم_العـمـيل { get; set; }
        public string المندوب { get; set; }
    }
}
