//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_PurchaseInvoicesArb
    {
        public int BranchID { get; set; }
        public int رقـم_الـفـاتـورة { get; set; }
        public string تاريخ_الفاتورة { get; set; }
        public string طريقـة_الـشـراء { get; set; }
        public string الـــمـــــــــــورد { get; set; }
        public int رقـم_فـاتـورة_المورد { get; set; }
        public string الـمـســـتـودع { get; set; }
        public string مـنـدوب_الـمـشـتريات { get; set; }
        public string مركز_الـتكلـفـة { get; set; }
    }
}
