//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_DiscountOnTotal
    {
        public int InvoiceID { get; set; }
        public double DiscountOnTotal { get; set; }
        public string month { get; set; }
        public string day { get; set; }
        public double InvoiceDate { get; set; }
        public int BranchID { get; set; }
    }
}
