//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_PurchaseInvoicesEng
    {
        public int BranchID { get; set; }
        public int Invoice_ID { get; set; }
        public string Invoice_Date { get; set; }
        public string Purchase_Method { get; set; }
        public string Supplier_Name { get; set; }
        public int Supplier_Invoice_ID { get; set; }
        public string Store_Name { get; set; }
        public string Purchase_Delegate { get; set; }
        public string Cost_Center_Name { get; set; }
    }
}
