//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
   public class Sales_PurchaseDiamondDetails
    {

        public int InvoiceID { get; set; }
        public string BarCode { get; set; }
        public string BarCodeItem { get; set; }

        public string ArbItemName { get; set; }

        public decimal WeightIn { get; set; }
        public decimal WeightOut { get; set; }
        public decimal PriceCarat { get; set; }
        public decimal TotalPrice { get; set; }
        public double SupplierID { get; set; }
        
        public int Cancel { get; set; }
        public int ItemID { get; set; }
        public int BranchID { get; set; }
        public int StoreID { get; set; }
        public int FacilityID { get; set; }
      
        public int TypeOpration { get; set; }
        public string CaptionOpration { get; set; }
        public List<Sales_PurchaseDiamondDetails> DiamondDatails{ get; set; }
    


    }
}
