//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_PurchaseOrderArb
    {
        public int BranchID { get; set; }
        public int رقم_الطلب { get; set; }
        public string تاريـخ_الطلب { get; set; }
        public string تاريـخ_التسـليم { get; set; }
        public string اسـم_المــورد { get; set; }
        public string طـريقة_الشـحن { get; set; }
        public string شـروط_الشـن { get; set; }
    }
}
