
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Sales_PurchaseInvoiceSaveReturnMaster
    {
        public int InvoiceID { get; set; }
        public int BranchID { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public string InvoiceDate { get; set; }
        public Nullable<int> MethodeID { get; set; }
        public Nullable<double> SupplierID { get; set; }
        public Nullable<int> SupplierInvoiceID { get; set; }
        public Nullable<int> CostCenterID { get; set; }
        public Nullable<double> DelegateID { get; set; }
        public int StoreID { get; set; }
        public string Notes { get; set; }
        public Nullable<double> DebitAccount { get; set; }
        public Nullable<double> CreditAccount { get; set; }
        public Nullable<double> DiscountCreditAccount { get; set; }
        public Nullable<double> TransportDebitAccount { get; set; }
        public Nullable<double> TransportDebitAmount { get; set; }
        public string NetProcessID { get; set; }
        public string CheckID { get; set; }
        public Nullable<double> CheckAccount { get; set; }
        public Nullable<double> AdditionalAccount { get; set; }
        public Nullable<double> NetAccount { get; set; }
        public string CheckSpendDate { get; set; }
        public string WarningDate { get; set; }
        public byte[] InvoiceImage { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<double> RegDate { get; set; }
        public Nullable<double> RegTime { get; set; }
        public Nullable<int> EditUserID { get; set; }
        public Nullable<double> EditTime { get; set; }
        public Nullable<double> EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public Nullable<int> Cancel { get; set; }
        public string ReceiveDate { get; set; }
        public int Posted { get; set; }
        public Nullable<int> PageNo { get; set; }
        public Nullable<int> ItemStatus { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> NetType { get; set; }
        public Nullable<double> DiscountOnTotal { get; set; }
        public Nullable<double> AdditionaAmountTotal { get; set; }
        public Nullable<double> InvoiceTotal { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public Nullable<double> NetBalance { get; set; }
        public string VATID { get; set; }
        public Nullable<double> RegistrationNo { get; set; }
        public Nullable<double> InvoiceGoldTotal { get; set; }
        public Nullable<double> InvoiceEquivalenTotal { get; set; }
        public Nullable<double> InvoiceDiamondTotal { get; set; }
        public Nullable<double> WeightDiamondTotal { get; set; }
        public Nullable<double> WeightGoldTotal { get; set; }
        public Nullable<double> CreditGoldAccountID { get; set; }
        public Nullable<int> GoldUsing { get; set; }
        public string Mobile { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> CurencyID { get; set; }
        public Nullable<double> DebitGoldAccountID { get; set; }

        public List<Sales_PurchaseSaveInvoiceReturnDetails> PurchaseSaveReturnDatails { get; set; }
    }
}

