//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_PriceOffersMaster
    {
        public double OfferID { get; set; }
        public int BranchID { get; set; }
        public double OfferDate { get; set; }
        public int OfferPeriod { get; set; }
        public int StatusID { get; set; }
        public double CustomerID { get; set; }
        public string AuthorizedPerson { get; set; }
        public string EMail { get; set; }
        public string Subject { get; set; }
        public int DelegateID { get; set; }
        public int OfficialContactID { get; set; }
        public int InstallationPeriod { get; set; }
        public string Notes { get; set; }
        public string AdditionalDescription { get; set; }
        public Nullable<double> DiscountOnTotal { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
        public string Conditions { get; set; }
    }
}
