//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_PurchaseOrderEng
    {
        public int BranchID { get; set; }
        public int Order_ID { get; set; }
        public string Order_Date { get; set; }
        public string Delivery_Date { get; set; }
        public string Supplier_Name { get; set; }
        public string Shipping_Method { get; set; }
        public string Shipping_Terms { get; set; }
    }
}
