
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    public partial class Sales_PurchaseSaveInvoiceReturnDetails
    {
        public int ID { get; set; }
        public string BarCode { get; set; }
        public Nullable<int> Cancel { get; set; }
        public string Serials { get; set; }
        public int GroupID { get; set; }

        public string ArbGroupName { get; set; }
        public string EngGroupName { get; set; }
        public string ArbItemName { get; set; }
        public string EngItemName { get; set; }
        public string Color { get; set; }
        public string CLARITY { get; set; }
        public string ArbSizeName { get; set; }
        public string EngSizeName { get; set; }
        public int InvoiceID { get; set; }
        public int BranchID { get; set; }
        public int FacilityID { get; set; }
        public int ItemID { get; set; }
     
        public int SizeID { get; set; }
    
        public Nullable<double> ExpiryDate { get; set; }
        public double Bones { get; set; }
        public int StoreID { get; set; }
        public decimal Discount { get; set; }
        public decimal SalePrice { get; set; }
        public double AdditionalValue { get; set; }
    
     
        public string Description { get; set; }
        public Nullable<int> PageNo { get; set; }
        public Nullable<int> HavVat { get; set; }
        public Nullable<int> ItemStatus { get; set; }
        public Nullable<double> Caliber { get; set; }
        public Nullable<double> Equivalen { get; set; }
        public Nullable<double> Net { get; set; }
        public Nullable<int> TheCount { get; set; }
        public Nullable<double> AdditionaAmmount { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Total { get; set; }

     
        public double QTY { get; set; }
      
        public Nullable<double> DIAMOND_W { get; set; }
        public Nullable<double> STONE_W { get; set; }
        public Nullable<double> BAGET_W { get; set; }
        public decimal CostPrice { get; set; }
        public Nullable<double> CaratPrice { get; set; }

        public Sales_PurchaseInvoiceSaveReturnMaster PurchaseSaveReturnMaster { get; set; }
    }
}

