//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_SalesInvoiceArb
    {
        public int BranchID { get; set; }
        public int رقـم_الـفـاتـورة { get; set; }
        public string تاريخ_الـفـاتـورة { get; set; }
        public string طريقـة_الـبـيـع { get; set; }
        public string الـمـســتـودع { get; set; }
        public string الــعـــمـــيــل { get; set; }
        public string الــبـــــــائــع { get; set; }
        public string مركز_الـتـكلـفـة { get; set; }
        public int MethodeID { get; set; }
    }
}
