//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_PriceOffersEng
    {
        public int BranchID { get; set; }
        public double Offer_ID { get; set; }
        public string Offer_Date { get; set; }
        public int Offer_Period { get; set; }
        public string Status { get; set; }
        public string Customer_Name { get; set; }
        public string Delegate { get; set; }
    }
}
