//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Customers
    {
        public readonly string TableName = "Sales_Customers";
        public readonly string PremaryKey = "CustomerID";

        public int CustomerID { get; set; }
        public int BranchID { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public Nullable<double> AccountID { get; set; }
        public int StopAccount { get; set; }
        public Nullable<double> TransactionDate { get; set; }
        public int  Category {get;set;}
        public int TypeCustomer {get;set;}
        public float BankAccountNo {get;set;}
        public string BankName  {get;set;}
        public int City {get;set;}
        public string Region {get;set;}
        public string CollectionDay {get;set;}
        public double ConductorID {get;set;}
        public double DelegateID { get; set; }
        public Nullable<double> ParentAccountID { get; set; }
        public string ArbName { get; set; }
        public string EngName { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Notes { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<double> RegDate { get; set; }
        public Nullable<double> RegTime { get; set; }
        public Nullable<int> EditUserID { get; set; }
        public Nullable<double> EditTime { get; set; }
        public Nullable<double> EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public Nullable<int> Cancel { get; set; }
        public Nullable<double> SpecialDiscount { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public string IdentityNumber { get; set; }
        public Nullable<int> IdentityTypeID { get; set; }
        public Nullable<double> IdentityExpiryDate { get; set; }
        public string CustomerType { get; set; }
        public Nullable<int> IsInBlackList { get; set; }
        public string BlockingReason { get; set; }
        public string VATID { get; set; }

        public decimal MaxLimit { get; set; }

        public int AllowMaxAgeDebt { get; set; }

        public int AllowMaxLimit { get; set; }

        public decimal MaxAgeDebt { get; set; }
    }
}
