//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schema_RecevMony
    {
        public double RecevMonyID { get; set; }
        public double DateRecive { get; set; }
        public double FromDate { get; set; }
        public double ToDate { get; set; }
        public int TypeRecive { get; set; }
        public int CostCenterID { get; set; }
        public string Region { get; set; }
        public double Mony { get; set; }
        public double AccountRecivePrevios { get; set; }
        public double AccountReciveNew { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditDate { get; set; }
        public double EditTime { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
        public int BranchID { get; set; }
        public double CustomerID { get; set; }
    }
}
