//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schema_ContractSchema
    {
        public double ContractID { get; set; }
        public double ContractDate { get; set; }
        public string Firsbox { get; set; }
        public string FirsTel { get; set; }
        public string FirsAddress { get; set; }
        public string Firsxg { get; set; }
        public string FirsPerson { get; set; }
        public double CustomerID { get; set; }
        public string FirsNotes { get; set; }
        public string SecoundName { get; set; }
        public string SecoundXg { get; set; }
        public string SecoundAddress { get; set; }
        public string SecoundBox { get; set; }
        public string SecoundTel { get; set; }
        public string SecoundMobile { get; set; }
        public string SecoundPerson { get; set; }
        public string SecoundNotes { get; set; }
        public string Notes { get; set; }
        public string SaveMony { get; set; }
        public string Total { get; set; }
        public string UnitTotal { get; set; }
        public string FirsMobile { get; set; }
        public int Cancel { get; set; }
        public int BranchID { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public double EditUserID { get; set; }
        public double EditDate { get; set; }
        public double EditTime { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public string RequestExecute { get; set; }
    }
}
