//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_RecipientGroupsMaster
    {
        public int GroupID { get; set; }
        public int BranchID { get; set; }
        public string ArbName { get; set; }
        public string EngName { get; set; }
        public string DefualtMessage { get; set; }
        public int chkCustomers { get; set; }
        public int chkSellers { get; set; }
        public int chkSalesDelegates { get; set; }
        public int chkSupplier { get; set; }
        public int chkPurchaseDelegates { get; set; }
        public int chkEmployees { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
    }
}
