//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_RecipientGroupsDetails
    {
        public int ID { get; set; }
        public int GroupID { get; set; }
        public int BranchID { get; set; }
        public int RecipientID { get; set; }
        public string RecipientName { get; set; }
        public string Mobile { get; set; }
        public string EMail { get; set; }
    }
}
