//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Stc_ItemsMoviing
    {
        public int MoveID { get; set; }
        public string MoveDate { get; set; }
        public int MoveType { get; set; }
        public int DocumentTypeID { get; set; }
        public int TranseID { get; set; }
        public int ID { get; set; }
        public int ItemID { get; set; }
        public int SizeID { get; set; }
        public double GroupID { get; set; }
        public string BarCode { get; set; }
        public int CostCenterID { get; set; }
        public double InPrice { get; set; }
        public double OutPrice { get; set; }
        public double QTY { get; set; }
        public double Bones { get; set; }
        public double StoreID { get; set; }
        public double AccountID { get; set; }
        public int BranchID { get; set; }
        public int FacilityID { get; set; }
        public Nullable<double> ExpiryDate { get; set; }
        public Nullable<int> Cancel { get; set; }
        public List<Stc_ItemsMoviing> ObjDatails { get; set; }

        public int Posted { get; set; }
    }
}


 
