//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stc_Items_Find
    {
        public int ItemID { get; set; }
        public string BarCode { get; set; }
        public string EngItemName { get; set; }
        public string EngItemType { get; set; }
        public string EngItemGroup { get; set; }
        public string ArbItemName { get; set; }
        public string ArbItemType { get; set; }
        public string ArbItemGroup { get; set; }
        public string ArbSizeName { get; set; }
        public string EngSizeName { get; set; }
    }
}
