//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public   class STC_STORESBO
    {
    
        public long ID { get; set; }
        public string ARBNAME { get; set; }
        public string ENGNAME { get; set; }
        public string ADDRESS { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public Nullable<decimal> STOREMANGER { get; set; }
        public string MOBILE { get; set; }
        public string NOTES { get; set; }
        public decimal BRANCHID { get; set; }
        public short DELETED { get; set; }
        public string DATECREATED { get; set; }
        public string DATEUPDATED { get; set; }
        public string DATEDELETED { get; set; }
        public Nullable<decimal> USERCREATED { get; set; }
        public Nullable<decimal> USERUPDATED { get; set; }
        public Nullable<decimal> USERDELETED { get; set; }
        public long CODE { get; set; }
    
        public STC_STORESBO(int ID, string ARBNAME, string ENGNAME, string NOTES)
        {
            this.ID = ID;
            this.ARBNAME = ARBNAME;
            this.ENGNAME = ENGNAME;
            this.NOTES = NOTES;
        }

        public STC_STORESBO()
        {
            this.ID = 0;
            this.ARBNAME = "";
            this.ENGNAME = "";
            this.NOTES = "";
        
        }

      


    }


}
