//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Stc_ManuFactoryCommendOutOnBail_Master
    {
        public int InvoiceID { get; set; }
        public int BranchID { get; set; }
        public int CommandID { get; set; }
        public int ReferanceID { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public Nullable<double> InvoiceDate { get; set; }
        public Nullable<int> CostCenterID { get; set; }
        public double StoreID { get; set; }
        public string Notes { get; set; }
        public Nullable<double> DebitAccount { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<double> RegDate { get; set; }
        public Nullable<double> RegTime { get; set; }
        public Nullable<int> EditUserID { get; set; }
        public Nullable<double> EditTime { get; set; }
        public Nullable<double> EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public Nullable<int> Cancel { get; set; }
        public int Posted { get; set; }
        public int TypeCommand { get; set; }
        public int DocumentType { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<double> RegistrationNo { get; set; }


        public List<Stc_ManuFactoryCommendOutOnBail_Details> CommandOutOnBailDatails { get; set; }
    }
}
