//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stc_ItemsGroups
    {
        public readonly string TableName = "Stc_ItemsGroups";
        public readonly string PremaryKey = "GroupID";
        public string GroupID { get; set; }
        public string ArbName { get; set; }
        public string EngName { get; set; }
        public string Notes { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
        public int BranchID { get; set; }
        public int FacilityID { get; set; }

        public string ParentAccountID { get; set; }
        public int AccountLevel { get; set; }
        public int AccountTypeID { get; set; }
        public int StopAccount { get; set; }
        public double MinLimit { get; set; }
        public double MaxLimit { get; set; }
    }
     
     
}
