//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stc_Stores
    {
        public readonly string TableName = "Stc_Stores";
        public readonly string PremaryKey = "StoreID";
        public Nullable<double> AccountID { get; set; }
        public Nullable<double> ParentAccountID { get; set; }
        public int StoreID { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string ArbName { get; set; }
        public string EngName { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string StoreManger { get; set; }
        public string Mobile { get; set; }
        public string Notes { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<double> RegDate { get; set; }
        public Nullable<double> RegTime { get; set; }
        public Nullable<int> EditUserID { get; set; }
        public Nullable<double> EditTime { get; set; }
        public Nullable<double> EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public Nullable<int> Cancel { get; set; }



        public int StopAccount { get; set; }
    }
}
