//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stc_ItemsDismantlingDetails
    {
      
        public string FromBarCode { get; set; }
        public int ItemID { get; set; }
        public string ArbItemName { get; set; }
        public string EngItemName { get; set; }
        public int SizeID { get; set; }
        public string ArbSizeName { get; set; }
        public string EngSizeName { get; set; }
        public int PackingQty { get; set; }
        public double QTY { get; set; }

        public DateTime ExpiryDate { get; set; }

        public int AnotherSizeID { get; set; }
        public string EngAnotherSizeName { get; set; }
        public string ArbAnotherSizeName { get; set; }
        public int AnotherPackingQty { get; set; }
        public double DismantledQTY { get; set; }
        public string Description { get; set; }
  
       
        public int ID { get; set; }
        public int StoreID { get; set; }
        public int DismantleID { get; set; }
        public string ToBarCode { get; set; }
        public long ExpiryDateStr { get; set; }
        public int BranchID { get; set; }
        public int FacilityID { get; set; }
        public int Cancel { set; get; }  
   
        public Stc_ItemsDismantlingMaster ItemsDismantlingMaster { get; set; }

        public Stc_ItemsDismantlingDetails()
        {

            ID = 0;
            ItemID = 0;
            DismantleID = 0;
            FromBarCode = "";
            ToBarCode = "";
            EngItemName = "";
            ArbItemName = "";
            SizeID = 1;
            ArbSizeName = "";
            EngSizeName = "";
            QTY = 1;
            AnotherPackingQty = 0;
            AnotherSizeID = 0;
         
            DismantledQTY = 0;
         
            FacilityID = 1;
            StoreID = 1;
            Cancel = 0;

            EngAnotherSizeName = "";
            ArbAnotherSizeName = "";
            Description = "";
            ExpiryDate = DateTime.Now;

        }
    
    }

}
