//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Stc_Items
    {
        public long ItemID { get; set; }
        public string ArbName { get; set; }
        public string EngName { get; set; }
        public double GroupID { get; set; }
        public int TypeID { get; set; }
        public int BrandID { get; set; }
        public int BaseID { get; set; }
        public string Notes { get; set; }
        public byte[] ItemImage { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
        public int IsVAT { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public List<Stc_ItemUnits> Stc_ItemUnits { get; set; }
        public string TypeName { get; set; }
        public string GroupName { get; set; }
        public byte[] picItemImage { get; set; }
        public bool boolVAT
        {
            get { return IsVAT == 1; }
            set
            {
                if (value)
                   IsVAT = 1;
                else
                   IsVAT = 0;
            }
        }
        public bool boolCancel
        {
            get { return Cancel == 1; }
            set
            {
                if (value)
                    Cancel = 1;
                else
                    Cancel = 0;
            }
        }
        public double RemindQty { get; set; }
        public string SizeName { get; set; }
        public string ExpiryDate { get; set; }
        public double SalePrice { get; set; }
        public double CostPrice { get; set; }
        public string BarCode { get; set; }

        public double BAGET_W { get; set; }
        public double STONE_W { get; set; }
        public double DIAMOND_W { get; set; }
        public double ZIRCON_W { get; set; }


        public int ItemGroupID { get; set; }

        public int IsService { get; set; }

        public int StopeItem { get; set; }

        public int IsUnbreakable { get; set; }

        public int ShowInOrderDetils { get; set; }
    }

}
