//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Edex.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Stc_ItemUnits
    {
        public int ID { get; set; }
        public string BarCode { get; set; }
        public long ItemID { get; set; }
        public int SizeID { get; set; }
        public string ArbSizeName { get; set; }
        public string EngSizeName { get; set; }
        public decimal PackingQty { get; set; }

        public decimal MinLimitQty { get; set; }
        public decimal MaxLimitQty { get; set; }

        public decimal CostPrice { get; set; }
        public decimal SalePrice { get; set; }

        public decimal LastCostPrice { get; set; }
        public decimal LastSalePrice { get; set; }
        public decimal SpecialSalePrice { get; set; }
        public decimal SpecialCostPrice { get; set; }
        public decimal AverageCostPrice { get; set; }

        public decimal ItemProfit { get; set; }
        public double AllowedPercentDiscount { get; set; }

        public int UnitCancel { get; set; }

        public double Caliber { get; set; }
        public double Equivalen { get; set; }
        public double BAGET_W { get; set; }
        public double STONE_W { get; set; }
        public double DIAMOND_W { get; set; }
        public double ZIRCON_W { get; set; }
        public double Width { get; set; }
        public double Height { get; set; }


        public int FacilityID { set; get; }
        public int BranchID { set; get; }


        public string Serials { get; set; }

        public string CLARITY { get; set; }
        public string Color { get; set; }
        public Stc_Items Stc_Items { get; set; }

    }


    public partial class Stc_ItemBarcode
    {

        public string BarcodeSecound { get; set; }
        public string ArbName { get; set; }
        public string ArbSizeName { get; set; }
        public string CostPrice { get; set; }
        public string Qty { get; set; }
        public string Hadr { get; set; }

        public int ItemID { get; set; }
        public string BarCode { get; set; }
      
        public string SalePrice { get; set; }
        public Int32 SizeID { get; set; }
    }
}
