//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stc_ArbItems_Find
    {
        public int رقم_الماده { get; set; }
        public string اسم_الماده { get; set; }
        public string الباركود { get; set; }
        public string المجموعه { get; set; }
        public string الـنــوع { get; set; }
    }
}
