//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Stc_ItemsTransferDetails
    {
        public int ID { get; set; }
        public int InvoiceID { get; set; }
        public int BranchID { get; set; }
        public int FacilityID { get; set; }


        public string BarCode { get; set; }
        public int ItemID { get; set; }

        public string ArbItemName { get; set; }
        public string EngItemName { get; set; }

        public string EngSizeName { get; set; }
        public string ArbSizeName { get; set; }

        public int SizeID { get; set; }
        public decimal  QTY { get; set; }
        public decimal SalePrice { get; set; }
        public decimal Bones { get; set; }

        public int FromStoreID { get; set; }
        public int ToStoreID { get; set; }

        public DateTime  ExpiryDate { get; set; }
        public decimal CostPrice { get; set; }
        public decimal Total { get; set; }
        public string Description { get; set; }
        public decimal Height { get; set; }
        public decimal Width { get; set; }
        public decimal TheCount { get; set; }
        public string Serials { get; set; }
        public decimal AdditionalValue { get; set; }
        public decimal Discount { get; set; }
        public decimal PrecentDiscount { get; set; }
        public int Cancel { get; set; }
        public long ExpiryDateStr { get; set; }
        public Stc_ItemsTransferMaster ItemsOutonBailMaster { get; set; }


    }
}
