//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stc_ItemSizingUnitsEng_Find
    {
        public int ItemID { get; set; }
        public Nullable<int> Unit_ID { get; set; }
        public string Unit_Name { get; set; }
    }
}
