//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Stc_ItemsTransferMaster
    {
        public int InvoiceID { get; set; }
        public int BranchID { get; set; }
        public int FacilityID { get; set; }

        public string InvoiceDate { get; set; }
        public int MethodeID { get; set; }
        public double CustomerID { get; set; }
        public int CurencyID { get; set; }
        public int CostCenterID { get; set; }
        public int SellerID { get; set; }
        public int FromStoreID { get; set; }
        public int ToStoreID { get; set; }

        public decimal DelegateID { get; set; }
        public string Notes { get; set; }
        public decimal DiscountOnTotal { get; set; }
        public double DebitAccount { get; set; }
        public double CreditAccount { get; set; }
        public double DiscountDebitAccount { get; set; }
        public double AdditionalAccount { get; set; }

        public int FromCashierScreen { get; set; }
        public int CloseCashier { get; set; }
        public double CloseCashierDate { get; set; }
        public string NetProcessID { get; set; }
        public string CheckID { get; set; }
        public double CheckAccount { get; set; }

        public string CheckSpendDate { get; set; }
        public string WarningDate { get; set; }
        public int DailyID { get; set; }
        public string OrderType { get; set; }
        public int SectionID { get; set; }
        public int TableID { get; set; }
        public int NeedReview { get; set; }
        public string ReviewType { get; set; }
        public int IsSendReview { get; set; }
        public string WorkDetails { get; set; }
        public string Status { get; set; }
        public int DocumentID { get; set; }
        public int UserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public int Cancel { get; set; }
        public double EmployeeID { get; set; }
        public double PateintID { get; set; }
        public double TempInvoiceID { get; set; }
        public double EnduranceRatio { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public Nullable<double> NetAccount { get; set; }

        public string CostCenterName { get; set; }
        public string StoreName { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> Descount { get; set; }
        public Nullable<decimal> Net { get; set; }
        public string SaleMethod { get; set; }
        public Nullable<decimal> NetBalance { get; set; }
        public List<Stc_ItemsTransferDetails> OutonBailDetails { get; set; }
    }
}
