//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StickersSettings
    {
        public int BranchID { get; set; }
        public string PrintCompanyName { get; set; }
        public int PrintItemName { get; set; }
        public int PrintExpiryDate { get; set; }
        public int PrintSalePrice { get; set; }
        public int FontSize { get; set; }
        public int FontBold { get; set; }
        public int BarCodeHeight { get; set; }
        public int StartFrom { get; set; }
    }
}
