//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMenusPermissions
    {
        public int UserID { get; set; }
        public string MenuName { get; set; }
        public int MenuView { get; set; }
        public int BranchID { get; set; }
        public int FacilityID { get; set; }
    }
}
