//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserID { get; set; }
        public string ArbName { get; set; }
        public string EngName { get; set; }
        public string Password { get; set; }
        public int NumberAllowedDays { get; set; }
        public float AllowedDate { get; set; }
        public int IsActiveAllowedDays { get; set; }
        public int IsActive { get; set; }
        public int Cancel { get; set; }
        public double EmployeeID { get; set; }
        public int FacilityID { get; set; }
        public int BranchID { get; set; }
        public string Mobile { get; set; }
        public int Gender { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Notes { get; set; }
        public int AddByUserID { get; set; }
        public double RegDate { get; set; }
        public double RegTime { get; set; }
        public int EditUserID { get; set; }
        public double EditTime { get; set; }
        public double EditDate { get; set; }
        public string ComputerInfo { get; set; }
        public string EditComputerInfo { get; set; }
        public byte[] pic { get; set; }
        public string imageSrc { get; set; }

        public int CostCenterID { get; set; }
        public int SellerID { get; set; }
        public int StoreID { get; set; }
        public double MainBoxAccountID { get; set; }




    }
}
