 
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edex.Model
{
    using System;
    using System.Collections.Generic;

    public partial class UserFormsFovorite
    {

        public int UserID { get; set; }
        public string FormName { get; set; }
        public int FormFovorite { get; set; }
    
        public string ArbCaption { get; set; }
        public string EngCaption { get; set; }
        public int BranchID { get; set; }
        public int FacilityID { get; set; }

    }
}
